baseURL = 'https://www.jesseward.com/'
theme = "lynx"
title = "Home Of Jesse Ward"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Jesse Ward"
  headline = "Software Developer // Systems Guy // Music Nut"
  image = "portrait.jpg"
  links = [
    { mixcloud = {href = "https://www.mixcloud.com/jw76" , text = "Mixcloud"}},
    { lastfm = "https://www.last.fm/user/jw76"},
    { spotify = { href = "https://open.spotify.com/user/jw-76", text = "Spotify"}},
    { discogs = { href = "https://www.discogs.com/user/jward", text = "Discogs"}},
    { soundcloud = "https://soundcloud.com/jesseward" },
    { github = "https://github.com/jesseward" },
    { linkedin = "https://linkedin.com/in/sjesseward" },
    { instagram = "https://www.instagram.com/sjesseward"},
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true